spring:
  application:
    name: lk-social-club
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    url: "jdbc:postgresql://postgres:5432/fitcha"
    username: "postgres"
    password: "password"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    schemas: fitcha_card_service
    locations: "classpath:db/migration"
    enabled: true


